# Generated by Django 5.0.6 on 2024-05-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview_App', '0003_audiofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='audio',
            field=models.FileField(upload_to='recordings'),
        ),
    ]
